name: stackwallet
description: Stack Wallet

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.5.36+115

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  ffi: ^2.0.1
  mutex: ^3.0.0

  lelantus:
    path: ./crypto_plugins/flutter_liblelantus

  flutter_libmonero:
    path: ./crypto_plugins/flutter_libmonero

  cw_monero:
    path: ./crypto_plugins/flutter_libmonero/cw_monero

  cw_wownero:
    path: ./crypto_plugins/flutter_libmonero/cw_wownero

  cw_core:
    path: ./crypto_plugins/flutter_libmonero/cw_core

  flutter_libepiccash:
    path: ./crypto_plugins/flutter_libepiccash

#  firo_flutter:
#    git:
#      url: https://github.com/cypherstack/firo_flutter.git
#      ref: update
  #    path: ./crypto_plugins/firo_flutter

  bitcoindart:
    git:
      url: https://github.com/cypherstack/bitcoindart.git
      ref: 004d6f82dff7389b561e5078b4649adcd2d9c10f

  stack_wallet_backup:
    git:
      url: https://github.com/cypherstack/stack_wallet_backup.git
      ref: e4b08d2b8965a5ae49bd57f598fa9011dd0c25e9

  bip47:
    git:
      url: https://github.com/cypherstack/bip47.git
      ref: 87bb760be323228aed6ca7bd4532a709a4f10690

  # Utility plugins
#  provider: ^6.0.1
  http: ^0.13.4
  local_auth: ^1.1.10
  permission_handler: ^10.0.0
  flutter_local_notifications: ^9.4.0
  rxdart: ^0.27.3
#  filesystem_picker: ^3.0.0-beta.1
  zxcvbn: ^1.0.0
  dart_numerics: ^0.0.6

  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size

  # Bitcoin plugins
  bip39:
    git:
      url: https://github.com/cypherstack/stack-bip39.git
      ref: 3bef5acc21340f3cc78df0ad1dce5868a3ed68a5
  bitbox:
    git:
      url: https://github.com/Quppy/bitbox-flutter.git
      ref: ea65073efbaf395a5557e8cd7bd72f195cd7eb11
  bip32: ^2.0.0
  bech32:
    git:
      url: https://github.com/cypherstack/bech32.git
      ref: 22279d4bb24ed541b431acd269a1bc50af0f36a0
  bs58check: ^1.0.2

  # Storage plugins
  flutter_secure_storage: ^5.0.2
  hive: ^2.0.5
  hive_flutter: ^1.1.0
  path_provider: ^2.0.8

  # UI/Component plugins
  flutter_native_splash: ^2.2.4
  animations: ^2.0.2
  toast: ^0.1.5
  flare_flutter: ^3.0.2
  google_fonts: ^2.2.0
  url_launcher: ^6.0.5
  flutter_svg: ^1.0.1
  flutter_feather_icons: ^2.0.0+1
  flutter_spinkit: ^5.1.0
  decimal: ^2.1.0
  event_bus: ^2.0.0
  uuid: ^3.0.5
  flutter_rounded_date_picker: ^3.0.1
  crypto: ^3.0.2
  jsonrpc2: ^3.0.1
  barcode_scan2: ^4.2.0
  app_settings: ^4.1.1
  wakelock: ^0.6.2
  intl: ^0.17.0
  devicelocale: ^0.5.0
  device_info_plus: ^7.0.1
  keyboard_dismisser: ^3.0.0
  another_flushbar: ^1.10.28
  tuple: ^2.0.0
  flutter_riverpod: ^1.0.3
  qr_flutter: ^4.0.0
  share_plus: ^4.0.10
  emojis: ^0.9.9
  pointycastle: ^3.6.0
  package_info_plus: ^1.4.2
  lottie: ^1.3.0
#  shared_preferences: ^2.0.15
  file_picker: ^5.0.1
  connectivity_plus: 2.3.6+1
#  document_file_save_plus: ^1.0.5
  isar: 3.0.5
  isar_flutter_libs: 3.0.5 # contains the binaries
  dropdown_button2: 1.7.2
  string_validator: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
      sdk: flutter
  build_runner: ^2.1.7
  flutter_launcher_icons: ^0.11.0
  hive_generator: ^1.1.2
  dependency_validator: ^3.1.2
  hive_test: ^1.0.1
  mockito: ^5.1.0
  mockingjay: ^0.2.0
#  lint: ^1.10.0
  analyzer: ^4.6.0
  import_sorter: ^4.6.0
  flutter_lints: ^2.0.1
  isar_generator: 3.0.5

flutter_icons:
  android: true
  ios: true
  image_path: assets/icon/icon.png
  image_path_android: assets/icon/app_icon_alpha.png
  image_path_ios: assets/icon/icon.png
  remove_alpha_ios: true
  windows:
    generate: true
    image_path: assets/icon/icon.png
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: assets/icon/icon.png

flutter_native_splash:
  image: assets/images/splash.png
  color: "F7F7F7"
  android_disable_fullscreen: true

dependency_overrides:
  bip39:
    git:
      url: https://github.com/cypherstack/stack-bip39.git
      ref: 3bef5acc21340f3cc78df0ad1dce5868a3ed68a5
  crypto: 3.0.2
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
    - assets/images/splash.png
    - assets/icon/icon.png
    - google_fonts/
    - assets/svg/circle-check.svg
    - assets/svg/clipboard.svg
    - assets/images/stack.png
    - assets/images/unclaimed.png
    - assets/images/monero.png
    - assets/images/wownero.png
    - assets/images/firo.png
    - assets/images/litecoin.png
    - assets/images/doge.png
    - assets/images/bitcoin.png
    - assets/images/epic-cash.png
    - assets/images/bitcoincash.png
    - assets/images/namecoin.png
    - assets/images/particl.png
    - assets/images/glasses.png
    - assets/images/glasses-hidden.png
    - assets/svg/plus.svg
    - assets/svg/gear.svg
    - assets/svg/bell.svg
    - assets/svg/arrow-left-fa.svg
    - assets/svg/copy-fa.svg
    - assets/svg/star.svg
    - assets/svg/x-circle.svg
    - assets/svg/check.svg
    - assets/svg/alert-circle.svg
    - assets/svg/alert-circle2.svg
    - assets/svg/arrow-down-left.svg
    - assets/svg/arrow-up-right.svg
    - assets/svg/bars.svg
    - assets/svg/filter.svg
    - assets/svg/pending.svg
    - assets/svg/signal-stream.svg
    - assets/svg/Ellipse-43.svg
    - assets/svg/Ellipse-42.svg
    - assets/svg/arrow-rotate.svg
    - assets/svg/arrow-rotate2.svg
    - assets/svg/qrcode1.svg
    - assets/svg/gear-3.svg
    - assets/svg/swap.svg
    - assets/svg/chevron-down.svg
    - assets/svg/chevron-up.svg
    - assets/svg/lock-keyhole.svg
    - assets/svg/lock-open.svg
    - assets/svg/rotate-exclamation.svg
    - assets/svg/folder-down.svg
    - assets/svg/network-wired.svg
    - assets/svg/network-wired-2.svg
    - assets/svg/address-book.svg
    - assets/svg/address-book2.svg
    - assets/svg/arrow-right.svg
    - assets/svg/delete.svg
    - assets/svg/dollar-sign.svg
    - assets/svg/sun-bright2.svg
    - assets/svg/language2.svg
    - assets/svg/pen-solid-fa.svg
    - assets/svg/magnifying-glass.svg
    - assets/svg/x.svg
    - assets/svg/x-fat.svg
    - assets/svg/user.svg
    - assets/svg/user-plus.svg
    - assets/svg/user-minus.svg
    - assets/svg/trash.svg
    - assets/svg/eye.svg
    - assets/svg/eye-slash.svg
    - assets/svg/folder.svg
    - assets/svg/calendar-days.svg
    - assets/svg/circle-question.svg
    - assets/svg/info-circle.svg
    - assets/svg/key.svg
    - assets/svg/node-alt.svg
    - assets/svg/signal-problem-alt.svg
    - assets/svg/signal-sync-alt.svg
    - assets/svg/wallet-settings.svg
    - assets/svg/ellipsis-vertical1.svg
    - assets/svg/dice-alt.svg
    - assets/svg/circle-arrow-up-right2.svg
    - assets/svg/loader.svg
    - assets/svg/add-backup.svg
    - assets/svg/auto-backup.svg
    - assets/svg/restore-backup.svg
    - assets/svg/sliders-solid.svg
    - assets/svg/message-question.svg
    - assets/svg/envelope.svg
    - assets/svg/share-2.svg
    - assets/svg/tx-icon-anonymize.svg
    - assets/svg/tx-icon-anonymize-pending.svg
    - assets/svg/tx-icon-anonymize-failed.svg
    - assets/svg/Polygon.svg
    - assets/svg/persona-easy-1.svg
    - assets/svg/persona-incognito-1.svg
    - assets/svg/Button.svg
    - assets/svg/enabled-button.svg
    - assets/svg/lock-circle.svg
    - assets/svg/dollar-sign-circle.svg
    - assets/svg/language-circle.svg
    - assets/svg/rotate-circle.svg
    - assets/svg/sun-circle.svg
    - assets/svg/node-circle.svg
    - assets/svg/address-book-desktop.svg
    - assets/svg/about-desktop.svg
    - assets/svg/exchange-desktop.svg
    - assets/svg/wallet-desktop.svg
    - assets/svg/exit-desktop.svg
    - assets/svg/keys.svg
    - assets/svg/arrow-down.svg
    - assets/svg/plus-circle.svg
    - assets/svg/circle-plus-filled.svg
    - assets/svg/configuration.svg
    - assets/svg/robot-head.svg
    - assets/svg/whirlpool.svg
    # coin icons
    - assets/svg/coin_icons/Bitcoin.svg
    - assets/svg/coin_icons/Litecoin.svg
    - assets/svg/coin_icons/Bitcoincash.svg
    - assets/svg/coin_icons/Dogecoin.svg
    - assets/svg/coin_icons/EpicCash.svg
    - assets/svg/coin_icons/Firo.svg
    - assets/svg/coin_icons/Monero.svg
    - assets/svg/coin_icons/Wownero.svg
    - assets/svg/coin_icons/Namecoin.svg
    - assets/svg/coin_icons/Particl.svg
    # lottie animations
    - assets/lottie/test.json
    - assets/lottie/test2.json
    # socials
    - assets/svg/socials/discord.svg
    - assets/svg/socials/reddit-alien-brands.svg
    - assets/svg/socials/twitter-brands.svg
    - assets/svg/socials/telegram-brands.svg
    - assets/svg/chevron-right.svg
    - assets/svg/minimize.svg
    - assets/svg/wallet-fa.svg
    - assets/svg/exchange-3.svg
    - assets/svg/message-question-1.svg
    - assets/svg/drd-icon.svg
    - assets/svg/box-auto.svg
    - assets/svg/framed-address-book.svg
    - assets/svg/framed-gear.svg
    # exchange icons
    - assets/svg/exchange_icons/change_now_logo_1.svg
    - assets/svg/exchange_icons/simpleswap-icon.svg

    # theme selectors
    - assets/svg/dark-theme.svg
    - assets/svg/light-mode.svg
    - assets/svg/ocean-breeze-theme.svg
    - assets/svg/oled-black-theme.svg
    - assets/svg/fruit-sorbet-theme.svg

    # light theme specific
    - assets/svg/light/tx-exchange-icon.svg
    - assets/svg/light/tx-exchange-icon-pending.svg
    - assets/svg/light/tx-exchange-icon-failed.svg
    - assets/svg/light/tx-icon-send.svg
    - assets/svg/light/tx-icon-send-pending.svg
    - assets/svg/light/tx-icon-send-failed.svg
    - assets/svg/light/tx-icon-receive.svg
    - assets/svg/light/tx-icon-receive-pending.svg
    - assets/svg/light/tx-icon-receive-failed.svg
    - assets/svg/light/exchange-2.svg
    - assets/svg/light/bell-new.svg
    - assets/svg/light/stack-icon1.svg
    - assets/svg/light/buy-coins-icon.svg

    # dark theme specific
    - assets/svg/dark/tx-exchange-icon.svg
    - assets/svg/dark/tx-exchange-icon-pending.svg
    - assets/svg/dark/tx-exchange-icon-failed.svg
    - assets/svg/dark/tx-icon-send.svg
    - assets/svg/dark/tx-icon-send-pending.svg
    - assets/svg/dark/tx-icon-send-failed.svg
    - assets/svg/dark/tx-icon-receive.svg
    - assets/svg/dark/tx-icon-receive-pending.svg
    - assets/svg/dark/tx-icon-receive-failed.svg
    - assets/svg/dark/exchange-2.svg
    - assets/svg/dark/bell-new.svg
    - assets/svg/dark/stack-icon1.svg
    - assets/svg/dark/buy-coins-icon.svg

    # ocean theme specific
    - assets/svg/oceanBreeze/tx-exchange-icon.svg
    - assets/svg/oceanBreeze/tx-exchange-icon-pending.svg
    - assets/svg/oceanBreeze/tx-exchange-icon-failed.svg
    - assets/svg/oceanBreeze/tx-icon-send.svg
    - assets/svg/oceanBreeze/tx-icon-send-pending.svg
    - assets/svg/oceanBreeze/tx-icon-send-failed.svg
    - assets/svg/oceanBreeze/tx-icon-receive.svg
    - assets/svg/oceanBreeze/tx-icon-receive-pending.svg
    - assets/svg/oceanBreeze/tx-icon-receive-failed.svg
    - assets/svg/oceanBreeze/exchange-2.svg
    - assets/svg/oceanBreeze/bell-new.svg
    - assets/svg/oceanBreeze/stack-icon1.svg
    - assets/svg/oceanBreeze/buy-coins-icon.svg
    - assets/svg/oceanBreeze/bg.svg

    # OLED black theme specific
    - assets/svg/oledBlack/tx-exchange-icon.svg
    - assets/svg/oledBlack/tx-exchange-icon-pending.svg
    - assets/svg/oledBlack/tx-exchange-icon-failed.svg
    - assets/svg/oledBlack/tx-icon-send.svg
    - assets/svg/oledBlack/tx-icon-send-pending.svg
    - assets/svg/oledBlack/tx-icon-send-failed.svg
    - assets/svg/oledBlack/tx-icon-receive.svg
    - assets/svg/oledBlack/tx-icon-receive-pending.svg
    - assets/svg/oledBlack/tx-icon-receive-failed.svg
    - assets/svg/oledBlack/exchange-2.svg
    - assets/svg/oledBlack/bell-new.svg
    - assets/svg/oledBlack/stack-icon1.svg
    - assets/svg/oledBlack/buy-coins-icon.svg

    # fruit sorbet theme specific
    - assets/svg/fruitSorbet/tx-exchange-icon.svg
    - assets/svg/fruitSorbet/tx-exchange-icon-pending.svg
    - assets/svg/fruitSorbet/tx-exchange-icon-failed.svg
    - assets/svg/fruitSorbet/tx-icon-send.svg
    - assets/svg/fruitSorbet/tx-icon-send-pending.svg
    - assets/svg/fruitSorbet/tx-icon-send-failed.svg
    - assets/svg/fruitSorbet/tx-icon-receive.svg
    - assets/svg/fruitSorbet/tx-icon-receive-pending.svg
    - assets/svg/fruitSorbet/tx-icon-receive-failed.svg
    - assets/svg/fruitSorbet/exchange-2.svg
    - assets/svg/fruitSorbet/bell-new.svg
    - assets/svg/fruitSorbet/stack-icon1.svg
    - assets/svg/fruitSorbet/buy-coins-icon.svg
    - assets/svg/fruitSorbet/bg.svg

    # buy
    - assets/svg/buy/Simplex-Nuvei-Logo.svg
    - assets/svg/buy/Simplex-Nuvei-Logo-light.svg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

import_sorter:
  comments: false # Optional, defaults to true
  ignored_files: # Optional, defaults to []
    - \/test\/*
    - \/crypto_plugins\/*
    - \/integration_test\/*
